### ISSUE TITLE
Payslip listing should be derived from earning with dynamic retrieval of the common earnings and deductions.

### ISSUE THREAD

**Issue by BytesCrafter** [BytesCrafter/erpat#120]

**Comment by BytesCrafter** [comment]
**Earnings**
basic_pay - Basic Pay
regular_overtime - Regular Overtime
restday_overtime - Restday Overtime
special_holiday - Special Holiday
regular_holiday - Regular Holiday
night_differential - Night Differential
paidtime_off - PaidTime Off

**Deductions**
unwork_deduction - Unwork Deduction
tax_due - Tax Due

**Comment by bcvalerick** [comment]
![image](https://github.com/BytesCrafter/erpat/assets/159507163/75e55dd5-7452-4f2f-b13e-49cb850d9c6a)
This is the sample and it works now
