### ISSUE TITLE
There is a localhost Datatables warning upon opening Sales/Services 

### ISSUE THREAD

**Issue by bcvalerick** [BytesCrafter/erpat#171]
![image](https://github.com/BytesCrafter/erpat/assets/159507163/b387a532-acef-473e-8952-cfa6a0e15721)

When you open the sub category services on category sales there is a localhost warning that says "DataTables warning: table id=services-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7".

**Comment by BytesCrafter** [comment]
Hello @bcvalerick I added a database migration for this issue Please update your database in Settings > Maintenance > Migrate Database to latest. Dont forget to git pull origin release

**Comment by bcvalerick** [comment]
Noted, Thank you for the information.
