### ISSUE TITLE
Payslips data must be freeze regardless of settings changes.

### ISSUE THREAD

**Issue by BytesCrafter** [BytesCrafter/erpat#30]
Instead of always recalculating payslip based on current data, calculate and save as precomputed data.
- This will also make sure that payroll will never changes even if some payroll parameters is changed.

**Comment by BytesCrafter** [comment]
There should be a payroll meta value that checked if the payroll instance already been basic pay computed then use that data else just always recalculate. This condition should also applied whether on payslip to use the recalculation or not.

**Comment by bcvalerick** [comment]
There is an investigate and override button now for manual calculations and individual logging of the earnings and deductions. While also changing salary the Payslip freezes.
![image](https://github.com/BytesCrafter/erpat/assets/159507163/5f9dd60b-3328-4ca9-a4ec-84ad525aedf0)
