### ISSUE TITLE
On all the new column for HD, it should work as intended to all attendance browser, optimized in BioMeet.

### ISSUE THREAD

**Issue by BytesCrafter** [BytesCrafter/erpat#77]

**Comment by bcvalerick** [comment]
![image](https://github.com/BytesCrafter/erpat/assets/159507163/6364db0a-b901-4069-8d50-ed5d452c669f)
![image](https://github.com/BytesCrafter/erpat/assets/159507163/bef68c12-0f8d-45a7-9a3e-d5f650c4784f)
Even there's a holiday it is not reflecting on the columns of the attendance browser
